#!/bin/bash
# The logic to stop your application should be put in this script.

PID_FILE=$OPENSHIFT_DATA_DIR/openscoring.pid

if [ -f $PID_FILE ]
then
    kill `cat $PID_FILE` > /dev/null 2>&1
    rm $PID_FILE
else
    echo "No PID file at $PID_FILE"
fi
